# Generated by Django 4.2.5 on 2023-09-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Done", "Done"),
                            ("In progress", "In progress"),
                            ("Not done", "Not done"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
