# Generated by Django 4.2.5 on 2023-09-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
