# Generated by Django 4.2.5 on 2023-09-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_todo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="name",
            field=models.CharField(max_length=300),
        ),
    ]
